name: CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
        with:
          version: 23.0.1
          shell: sh
          run: docker version