name: CI

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v1
        with:
          version: 23.0.1
          shell: sh
          run: docker run --publish 80:80 --name gitlab --hostname localhost wlsf82/gitlab-ce

    # steps:
    #   - name: Checkout GitCode
    #     uses: actions/checkout@v2
 
    #   - name: Run Cypress Test
    #     uses: cypress-io/github-action@v4
    #     with:
    #       command: npx cypress run
    #       browser: chrome